name: news_app_clean_architecture
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #icon
  ionicons: ^0.1.2

  #state management
  flutter_bloc: ^8.1.3

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.4

  #dateFormat
  intl: ^0.18.1

  #Database
  floor: any

  #make request to api
  retrofit: ^4.0.1

  #Hooks
  flutter_hooks: ^0.20.1

  #chached image
  cached_network_image: ^3.3.0
  reactive_forms: ^16.1.0

  #network
  dio_cookie_manager: ^3.1.0+1
  cookie_jar: ^4.0.8

  #routing
  auto_route: ^7.8.3

  #splash
  flutter_native_splash: ^2.3.2

  #redirect
  flutter_inappwebview: ^6.0.0-beta.21
  webview_flutter: ^4.4.1



flutter_native_splash:
  color: "#42A5F5"
  fill: true
  color_dark: "#845EC2"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  retrofit_generator: 7.0.8
  floor_generator: 1.4.2
  build_runner: 2.4.6
  pretty_dio_logger: ^1.3.1
  auto_route_generator: ^7.3.1

flutter:
  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
